#!/bin/bash

# Check if package.json has changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -E 'package.json' > /dev/null; then
  echo "package.json이 변경되었습니다. pnpm install을 실행합니다."
  pnpm install
fi